sonar.projectKey=contact-manager-frontend
sonar.projectName=Contact Manager Frontend
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_65ab21c632a724f11d6939261e447f43ae185838