sonar.projectKey=contact-managment-frontend
sonar.projectName=Contact Management Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_31e56b14aebd47f3421ad7fa34e9dbf51183d349